name: Build Binaries

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build Linux Binary
        run: pyinstaller --onefile --distpath ./bin/linux ./src/aliasify.py
      - name: Upload Linux Binary
        uses: actions/upload-artifact@v2
        with:
          name: aliasify-linux
          path: ./bin/linux/aliasify

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build macOS Binary
        run: pyinstaller --onefile --distpath ./bin/macos ./src/aliasify.py
      - name: Upload macOS Binary
        uses: actions/upload-artifact@v2
        with:
          name: aliasify-macos
          path: ./bin/macos/aliasify
